checkpoint: ../runs/next-token-256/checkpoints/latest.pt
output_directory: ../runs/next-token-256/variant-effects-step-75000

assay_paths:
  - ../datasets/benchmarks/evo1_prokaryotic/BLAT_ECOLX_Jacquier_2013.csv
  - ../datasets/benchmarks/evo1_prokaryotic/CCDB_ECOLI_Adkar_2012.csv
  - ../datasets/benchmarks/evo1_prokaryotic/KKA2_KLEPN_Melnikov_2014.csv

batch_size: 128
device: cuda:0

hydra:
  run:
    dir: ${output_directory}
