nsm_checkpoint: ../runs/nsm-256-40m/checkpoints/final.pt
tokenizer_checkpoint: ../runs/vqvae-128-block/checkpoints/final.pt
output_directory: ../runs/nsm-256-40m/variant-effects

assay_paths:
  - ../datasets/benchmarks/evo1_prokaryotic/BLAT_ECOLX_Jacquier_2013.csv
  - ../datasets/benchmarks/evo1_prokaryotic/CCDB_ECOLI_Adkar_2012.csv
  - ../datasets/benchmarks/evo1_prokaryotic/KKA2_KLEPN_Melnikov_2014.csv

batch_size: 128
device: cuda:0
prefix_length: null

hydra:
  run:
    dir: ${output_directory}
